# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UMC_Week7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UMC_Week7
  pod 'KakaoSDK'

  target 'UMC_Week7Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UMC_Week7UITests' do
    # Pods for testing
  end

end
