# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UMC_Week9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UMC_Week9
  pod 'Alamofire'

  target 'UMC_Week9Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UMC_Week9UITests' do
    # Pods for testing
  end

end
