# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chapter10' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.5'
  pod 'Kingfisher'
  pod 'SnapKit', '~> 5.0.0'
  # Pods for Chapter10

end
